name: Dataiku Predeployment Preparation

on:
  workflow_call:
    inputs:
      dss-project:
        description: "Dataiku Project ID"
        required: true
        type: string
      bundle-id:
        description: "Bundle ID generated in Preparation Step"
        required: true
        type: string
    secrets:
      design-api-key:
        required: true
      repo-token:
        required: true

env:
  # DSS_PROJECT: CICDPROJECT1
  design-url: https://dss-4e19401b-7badb918-dku.eu-west-3.app.dataiku.io
  # DESIGN_API_KEY: iIQsGcWDxzYOJE1s5soCBqdRErzzfJwR

jobs:
  package-bundle:
    name: Package Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'ProjectiveGroupUK/dataiku-cicd-actions'
          ref: 'main'
          token: ${{ secrets.repo-token }}

      - name: List files in this repository
        run: ls -la

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Create bundle
        run: python package_bundle/run_bundling.py '${{ env.design-url }}' '${{ secrets.design-api-key }}' '${{ inputs.dss-project }}' '${{ inputs.bundle-id }}'

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ${{ inputs.bundle-id }}.zip
