name: Trigger Scenario Stage

on:
  workflow_call:
    inputs:
      dss-project:
        description: "Dataiku Project ID"
        required: true
        type: string

env:
  node-url: https://dss-4e19401b-7badb918-dku.eu-west-3.app.dataiku.io

jobs:
  trigger-scenario:
    name: Trigger Scenario
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'ProjectiveGroupUK/dataiku-cicd-actions'
          ref: 'main'

      # - name: List files in this repository
      #   run: ls -la

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Trigger Scenario
        run: python trigger_scenario/run_scenario.py '${{ env.node-url }}' '${{ secrets.DESIGN_API_KEY }}' '${{ inputs.dss-project }}'
        
