name: Project Validation Stage

on:
  workflow_call:
    inputs:
      dss-project:
        description: "Dataiku Project ID"
        required: true
        type: string

env:
  node-url: https://dss-4e19401b-7badb918-dku.eu-west-3.app.dataiku.io

jobs:
  validate:
    name: Project Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "ProjectiveGroupUK/dataiku-cicd-actions"
          ref: "main"

      # - name: List files in this repository
      #   run: ls -la

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          python -m pytest 1_project_validation/run_test.py -o junit_family=xunit1 --host='${{ env.node-url }}' --api='${{ secrets.DESIGN_API_KEY }}' --project='${{ env.dss-project }}' --junitxml=reports/PROJECT_VALIDATION.xml
      
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Project validation test results
          path: reports/**/*.xml